### ISSUE TITLE
v0.8.3 checksum changed?

### ISSUE THREAD

**Issue by Clete2** [syncthing/syncthing-inotify#131]
Hello,
We noticed that the v0.8.3 checksum changed (See: https://github.com/Homebrew/homebrew-core/pull/5511). It seems the release was retagged a week ago, but the original release was back in July. Can you confirm this was intentional and necessary?

**Comment by imsodin** [comment]
Yes this was intentional due to #126.

**Comment by Clete2** [comment]
Thank you.

**Comment by MikeMcQuaid** [comment]
In future I ask if it's possible to not do this. If I `git fetch --tags` this repository then I won't receive retagged tags. Additionally, projects like Homebrew that rely on your tags to signify releases will see checksum failures that are unclear whether they are intentional (you've retagged) or unintentional (you've been hacked).
