### ISSUE TITLE
Server certificate not validated

### ISSUE THREAD

**Issue by Unrud** [syncthing/syncthing-inotify#140]
This tool is insecure on multi-user systems. Another user can simply listen on the same address:port as syncthing (before syncthing is started or when it gets restarted) and this tool will happily transmit the credentials. (Somewhat related to syncthing/syncthing#3616)

**Comment by spectras** [comment]
Related indeed. Having the API listen on a Unix socket in the user's configuration, or a namedpipe with proper ACL on Windows, would solve the issue entirely. And greatly improve performance as tools such as `syncthing-inotify` would not need to go through the network stack or do the TLS handshake over and over again, since a Unix socket/Windows pipe does not need TLS in the first place.

**Comment by Zillode** [comment]
@spectras please open a separate issue for your suggestion. It also requires upstream changes.
