### ISSUE TITLE
Adding this project to an openSUSE YaST repository?

### ISSUE THREAD

**Issue by rlue** [syncthing/syncthing-inotify#172]
Hi folks,

I just made the leap to Linux (openSUSE Tumbleweed) from Mac OS, so forgive my lack of knowledge on the matter:

I was able to install syncthing via the [official release repo](https://software.opensuse.org/package/syncthing), but there's no corresponding package for syncthing-inotify (nor is there one in the packman community repo).

Is there another repo managed by the syncthing maintainers for this package, so that I can keep up with updates without having to manually check the syncthing site? And if not, what would it take to get one?

Thanks in advance.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by rlue** [comment]
got it, thanks!
