### ISSUE TITLE
interval="100ms" no longer works?

### ISSUE THREAD

**Issue by mjm-cycronix** [syncthing/syncthing-inotify#177]
As of v0.8.5, the -interval flag seemed to work.  After updating to V0.8.7, the previously fast response of setting a short interval (e.g. -interval="100ms") changed from about the expected 100ms to 500ms.  We can look into further narrowing which version this changed and run more debugging tests, but perhaps there is an obvious fix?  Thanks so much, our application has up until recently very much benefited from the extremely fast responsiveness of syncthing-inotify!

**Comment by imsodin** [comment]
Yes, this happened in https://github.com/syncthing/syncthing-inotify/commit/f241889e20b8296abd408dcfdb07dfc7cbfca415. I don't understand the purpose of this commit, however adding `fsEventTimeout` was hardly intended. This variable was removed from all functions a very long time ago in https://github.com/syncthing/syncthing-inotify/commit/f241889e20b8296abd408dcfdb07dfc7cbfca415 but left as a unused global variable.

@Zillode It should probably be `debounceTimeout` instead of `fsEventTimeout` in
https://github.com/syncthing/syncthing-inotify/blob/master/syncwatcher.go#L757
or it should also be set by the -interval option.
