### ISSUE TITLE
Folders containing folders get locked on Windows

### ISSUE THREAD

**Issue by alexbeer2048** [syncthing/syncthing-inotify#23]
For Windows the SyncWatcher seems to lock the parent folder, which means you cannot edit/move/delete the parent folder, if the folder hierarchy is deeper then 1.

E.g.

```text
--FolderA
    --FolderB
        --SomeFile1.txt
```

In this example editing/renaming SomeFile1.txt and FolderB works fine, but FolderA can not be renamed, moved or deleted.
Windows complains that the folder or a file in it is being edited by another program and it should be closed before.

Language on my system is german so a can not give you the exact english error message.

OS: Windows 8.1
Go: version 1.4.2
Compiled syncthing and syncthing-inotify from the latest source. 

I just learned about the Syncthing project and I'm also new to Go programming language, so forgive me if I missed out on some basic things.

I hope someone with better knowledge can write a test for this scenario. Maybe it's only related to Windows, maybe it's also applies to linux and iOS.

**Comment by Zillode** [comment]
Probably related to https://github.com/syncthing/syncthing-inotify/issues/15

**Comment by alexbeer2048** [comment]
Might be. Sorry I missed that one.
In my test I only had the problem with folders though.

```text
--FolderA
    --SomeFile1.txt
    --FolderB
        --SomeFile2.txt
--SomeFile3.txt
```
Editing all these files works fine, only FolderA can not be changed, unless FolderB is removed or moved somewhere else before.

For example, if I want to delete FolderA, I would have to delete FolderB first and then FolderA.

**Comment by hakakou** [comment]
I've checked what is happening because this bug is a serious show stopper for me, as it results in not being able to delete folders with subfolders (I'm using windows).

To see this bug in action, it is important to create a test "top" folder with subdirectories, and delete the top folder from explorer. In this case the subfolders get locked and you need to restart inotify to delete them.

Note however that if you navigate the tree and delete the subfolders one by one, then the bug will not be active. This is because I assume inotify needs a few miliseconds to remove the lock on each subfolder deleted; so if you delete each one by yourself (like for example every second) there is no problem. However if a recursive deletion routine is run that navigates the entire tree and deletes everything very fast (like what happens in the background when you delete the top folder), then the problem arouses.

**Comment by alexbeer2048** [comment]
I hope this:[fsnotify milestone v3](https://github.com/go-fsnotify/fsnotify/milestones/v3%20Recursive) will help to solve the issue and also allow a more efficient implementation for OS with native recursive watcher support like windows.

**Comment by Zillode** [comment]
I didn't rule out a bug in this code yet as I didn't have time to look at it. Feel free to inspect the code

**Comment by Zillode** [comment]
Should be fixed in upstream and our beta release. Please try it out, thanks!
