### ISSUE TITLE
Seemingly unnecessary repeated changes to .stfolder

### ISSUE THREAD

**Issue by plouj** [syncthing/syncthing-inotify#67]
I've noticed that my laptop battery drains much quicker when I have syncthing-inotify running. Looking at its log I see a lot of repeated changes to the .stfolder file regardless of whether there are changes to the actual contents of the folder or not. Eg:

Starting with an empty folder ~/Public (with Folder ID "public-test"), syncthing-inotify output:
...
[OK] 15:10:18 Syncthing is indexing change in public-test: [.stfolder]
...
$ touch ~/Public/blah
...
[OK] 15:10:25 Syncthing is indexing change in public-test: [blah]
[OK] 15:10:25 Syncthing is indexing change in public-test: [.stfolder]
...
$ rm ~/Public/blah
...
[OK] 15:10:29 Syncthing is indexing change in public-test: [blah]
[OK] 15:10:30 Syncthing is indexing change in public-test: [.stfolder]
...

There is nothing else that should be touching .stfolder on my system so I'm guessing it's either syncthing itself or syncthing-inotify. I can't can't figure out why and how to stop it.

Maybe this is a syncthing issue: syncthing/syncthing#1965

**Comment by Zillode** [comment]
Have you got a folder with `RescanIntervalS` set to 10 in config.xml?

**Comment by plouj** [comment]
No, my ```rescanIntervalS``` is the default value of 60.

**Comment by Zillode** [comment]
Could you run with inotify with `-verbosity 4`?

**Comment by plouj** [comment]
Here's a filtered portion of the produced log:

```
$ grep -C1 "public-test\|Slowing down inotify timeout parameters for public-test\|Informing ST\: public-test\|Syncthing is indexing change in public-test" /tmp/s-i.log 
[DEBUG] 15:52:28 Installing watch for public-test
--
[TRACE] 15:52:28 Getting ignore patterns for public-test
--
[OK] 15:52:28 Watching public-test: /home/plouj/Public
--
[TRACE] 15:53:23 Informing ST: public-test: [.stfolder]
--
[DEBUG] 15:53:24 Ignoring .config/syncthing/index-v0.11.0.db/006685.log
[OK] 15:53:25 Syncthing is indexing change in public-test: [.stfolder]
--
[TRACE] 15:54:19 Requesting STEvents: 3392
[TRACE] 15:54:20 Informing ST: public-test: [.stfolder]
[TRACE] 15:54:20 Requesting STEvents: 3393
[OK] 15:54:20 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:54:20 Requesting STEvents: 3394
--
[TRACE] 15:55:15 Informing ST: public-test: [.stfolder]
--
[TRACE] 15:55:16 Requesting STEvents: 3434
[OK] 15:55:16 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:55:16 Requesting STEvents: 3438
--
[TRACE] 15:56:11 Informing ST: public-test: [.stfolder]
[TRACE] 15:56:11 Requesting STEvents: 3483
[TRACE] 15:56:11 Requesting STEvents: 3484
[OK] 15:56:11 Syncthing is indexing change in public-test: [.stfolder]
--
[TRACE] 15:57:04 Requesting STEvents: 3538
[TRACE] 15:57:06 Informing ST: public-test: [.stfolder]
[TRACE] 15:57:06 Requesting STEvents: 3539
[OK] 15:57:06 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:57:06 Requesting STEvents: 3540
--
[TRACE] 15:57:59 Requesting STEvents: 3595
[TRACE] 15:58:01 Informing ST: public-test: [.stfolder]
--
[TRACE] 15:58:02 Requesting STEvents: 3598
[OK] 15:58:02 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:58:02 Requesting STEvents: 3599
--
[TRACE] 15:58:57 Requesting STEvents: 3656
[TRACE] 15:58:57 Informing ST: public-test: [.stfolder]
[TRACE] 15:58:57 Requesting STEvents: 3657
[OK] 15:58:57 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:58:57 Requesting STEvents: 3658
--
[DEBUG] 15:59:51 Ignoring .config/syncthing/index-v0.11.0.db/006685.log
[TRACE] 15:59:52 Informing ST: public-test: [.stfolder]
--
[TRACE] 15:59:56 Requesting STEvents: 3707
[OK] 15:59:56 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 15:59:56 Requesting STEvents: 3712
--
[TRACE] 16:00:51 Informing ST: public-test: [.stfolder]
[TRACE] 16:00:51 Requesting STEvents: 3757
[OK] 16:00:51 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 16:00:51 Requesting STEvents: 3758
--
[TRACE] 16:01:46 Informing ST: public-test: [.stfolder]
[TRACE] 16:01:46 Requesting STEvents: 3793
[OK] 16:01:46 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 16:01:46 Requesting STEvents: 3795
```

**Comment by Zillode** [comment]
These -- lines, are they caused by changes in the public-test folder?

**Comment by plouj** [comment]
No, those -- lines are just from grep. I didn't want to pollute this thread with messages about my other folders. No file changes are happening in my public-test folder (as far as I know).

**Comment by plouj** [comment]
I've recompiled syncthing-inotify with:
```
+++ b/syncwatcher.go
@@ -629,6 +629,7 @@ func accumulateChanges(debounceTimeout, stRescanInterval tim
                                        Debug.Println("Slowing down inotify time
                                        currInterval = delayScanInterval
                                }
+                               Debug.Println("Extending nextScan interval for " + folder)
                                callback(folder, []string{".stfolder"}) // Perio
                                continue
                        }
```

And it's definitely showing up in the log:

```
$ grep -C1 "Extending nextScan interval for public-test\|Syncthing is indexing change in public-test\|Informing ST\: public-test" /tmp/s-i.log 
[TRACE] 16:14:05 Requesting STEvents: 4441
[DEBUG] 16:14:05 Extending nextScan interval for public-test
[TRACE] 16:14:05 Informing ST: public-test: [.stfolder]
[TRACE] 16:14:05 Requesting STEvents: 4442
[OK] 16:14:05 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 16:14:05 Requesting STEvents: 4443
--
[DEBUG] 16:15:00 Extending nextScan interval for public-test
[TRACE] 16:15:00 Informing ST: public-test: [.stfolder]
--
[TRACE] 16:15:00 Informing ST: notes: [.stfolder]
[OK] 16:15:01 Syncthing is indexing change in public-test: [.stfolder]
```

**Comment by Zillode** [comment]
could you print the currInterval as well? Use ```Printf("%v", currInterval)```

**Comment by plouj** [comment]
The only value I've seen for that is 55s:

```
[DEBUG] 16:37:10 Extending nextScan interval for public-test currInterval 55s
[TRACE] 16:37:10 Informing ST: public-test: [.stfolder]
[TRACE] 16:37:10 Requesting STEvents: 4948
[OK] 16:37:10 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 16:37:10 Requesting STEvents: 4949
--
[DEBUG] 16:38:05 Extending nextScan interval for public-test currInterval 55s
[TRACE] 16:38:05 Informing ST: public-test: [.stfolder]
[TRACE] 16:38:05 Requesting STEvents: 5018
[OK] 16:38:05 Syncthing is indexing change in public-test: [.stfolder]
[TRACE] 16:38:05 Requesting STEvents: 5020
--
[DEBUG] 16:39:00 Extending nextScan interval for public-test currInterval 55s
[TRACE] 16:39:00 Informing ST: public-test: [.stfolder]
```

**Comment by Zillode** [comment]
I think I know where the problem lies, but you are stripping too much from the logs. I think there are changes being tracked (either from Syncthing [ST] or the filesystem [FS]), but are later ignored (due to your ignore patterns maybe). This means inotify will set the timeout very low because it wants to inform syncthing asap. However, the actual changes are filtered, hence we try to delay scanning for Syncthing.

I will extend the logic for delaying scans a bit more, thanks.

**Comment by plouj** [comment]
Ok, thanks for your help. I've uploaded a full log from syncthing-inotify to: http://plouj.com/syncthing-inotify.log

Is it possible that this is happening because public-test (~/Public) is part of a larger folder called spice-home (~/) which has a lot of continuous changes (in the .mozilla/ subdirectory)?

Please let me know if you need more info.

**Comment by koppor** [comment]
After updating syncthing-inotify from a version approx. 1 month ago, the same thing happens here, too. - Win 8.1 with recent service packs and syncthing v0.11.9

**Comment by plouj** [comment]
Thanks! I no longer get a spam of .stfolder changes :)

For my curiosity, would you mind explaining how things work at the moment? I can't figure out from reading the code what problem the delayScan thing is trying to solve and how it does that. So far I only understand the part where every time that inotify (```waitForEvent```) sees a file change syncthing-inotify tells syncthing to rescan relevant subfolders of a folder (via ```informChange```).

**Comment by Zillode** [comment]
Great:)
The driving force behind inotify is based on reading from a go channel.
This can contain events from the [filesystem](https://github.com/syncthing/syncthing-inotify/blob/fa6ba15cbdfab99efc3d5ce26e711266c8ff0402/syncwatcher.go#L617) and from [Syncthing](https://github.com/syncthing/syncthing-inotify/blob/fa6ba15cbdfab99efc3d5ce26e711266c8ff0402/syncwatcher.go#L598).
If no changes occur after some [timeout](https://github.com/syncthing/syncthing-inotify/blob/fa6ba15cbdfab99efc3d5ce26e711266c8ff0402/syncwatcher.go#L633) we check if something needs to be done.

On any filesystem or syncthing event, we set the timeout value to 500ms. This is the timeframe that will aggregated all changes before sending an index request to syncthing. It has two purposes:
1. Accumulate filesystem changes in a single rest request. This is pretty smart as it will use a heuristic to index an entire folder, a folder hierarchy or individual files. The filesystem hierarcy is used to filter redundant events (e.g. if `f` is a new folder, all changes within f can be filtered). We also filter patterns that are matched by custom ignore patterns listed in Syncthing.
2. Filter filesystem events that are caused by Syncthing. This is a bit complex because we can receive filesystem events before syncthing informs us about a 'finish' event (and the other way around).

When no changes happen after all this filtering, we put inotify in a deep sleep. This is based on the delay scan interval. Basically, inotify tells Syncthing it should not rescan unless we tell it so. However, we cannot set this delay scan interval to infinite because if inotify exits, Syncthing would never scan the folder again. Therefore, the default value is set to 1h and inotify will renew this lease every 59m55s (which is in fact the timeout of the deep sleep). This delay request uses the .stfolder file because we know it exists and is empty (thus very cheap to check by Syncthing).
Note that every filesystem event, which cause a scan request, will automatically delay the rescan interval (so no scan of .stfolder is required for the next 59m55s).
