### ISSUE TITLE
syncthing-inotify can't find API key anymore

### ISSUE THREAD

**Issue by lfam** [syncthing/syncthing-inotify#76]
Until 0.6.6, syncthing-inotify had no trouble finding Syncthing's API key.

With 0.6.6, syncthing-inotify successfully sets up its watches, but the initial "index" POST to Syncthing fails:
````
[WARNING] 23:35:12 Error: HTTP POST forbidden. missing API key?
````
All further POSTs fail as well:
````
[WARNING] 23:36:28 Syncthing failed to index changes for  folder HTTP POST forbidden
````
I have tested this on Debian 8 (amd64 and armv7). My config.xml is in ````~/.config/syncthing/````

If I specify the API key on the command line, it works.

**Comment by rumpelsepp** [comment]
same here: 

```
Error: HTTP POST forbidden. missing API key?
```

**Comment by NapoleonWils0n** [comment]
The fix is to add the api key to the command line when you launch syncthing-notify

Log into the web ui and click the action button, then select setting and copy your api key
you need to run syncthing-inotify with -api="your-api-key" on the command line

stop syncthing-inotify
systemctl --user stop syncthing-inotify.service

edit you syncthing-inotify.service file 

sudo vim /usr/lib/systemd/user/syncthing-inotify.service

find this line:

ExecStart=/usr/bin/syncthing-inotify -logflags=0

then append this to the end of the command, replace api-key-from-webui-settings with your api-key
 -api="api-key-from-webui-settings" 

it should look something like this

ExecStart=/usr/bin/syncthing-inotify -logflags=0 -api="uxcYP98gjhgjhTRVVH7666-yutuy6sdk"

save the file and exit

reload the systemctl daemon so the change take effect
systemctl --user daemon-reload

start syncthing-inotify
systemctl --user status syncthing-inotify.service

I have outlined all the steps below

https://github.com/NapoleonWils0n/cerberus/blob/master/syncthing/syncthing.sh

**Comment by rumpelsepp** [comment]
Just updated the AUR package and installed 0.6.7; this fix does not work.
```
[WARNING] 19:53:02 Error: HTTP POST forbidden. missing API key?
[WARNING] 19:53:02 Error: HTTP POST forbidden. missing API key?
[WARNING] 19:53:02 Error: HTTP POST forbidden. missing API key?
```
https://aur4.archlinux.org/cgit/aur.git/commit/?h=syncthing-inotify&id=361f021f81c629b459fd7dbdda2b7edddce1754a

**Comment by Zillode** [comment]
Sorry, I cannot reproduce this on linux. Could you try adding ```fmt.Println(apiKey, getSTDefaultConfDir())``` just before the follow lines?
```
fmt.Println(apiKey, getSTDefaultConfDir())
if len(apiKey) > 0 {
                r.Header.Set("X-API-Key", apiKey)
        }
```

**Comment by Zillode** [comment]
Here is a linux 64bit build with that debug line enabled: http://wilma.vub.ac.be/~lhoste/syncthing/unofficial/syncthing-inotify-linux-debug

**Comment by lfam** [comment]
0.6.7 works for me, although I'm not sure why it prints the API key on stdout over and over again. Is that some debug tracing that was left in the regular build?

**Comment by Zillode** [comment]
@lfam thanks, I didn't have much time this weekend to properly test it. Updated the release build.

**Comment by rumpelsepp** [comment]
@ my other laptop now. syncthing-inotify works as intended now (0.6.7). I have to investigate what's causing the issue on my other machine…

**Comment by rumpelsepp** [comment]
I have rebuilt syncthing-inotify. Now it works; maybe I have build the wrong package. Sry.

**Comment by lfam** [comment]
> @lfam thanks, I didn't have much time this weekend to properly test it. Updated the release build.

Is the build without the debug tracing available online somewhere? Or are you saving those changes for the next release?

**Comment by Zillode** [comment]
@lfam I updated the release files
